- name: copy file via ssh key
  uses: ssgrandhi/Codedeploy@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    port: ${{ secrets.PORT }}
    key: ${{ secrets.KEY }}
    source: "./*"
    target: "/var/ww/html/"
